projetoDefinitivo/contatos/urls.py
from django.urls.conf import path
from contatos import views


app_name = "contatos"

urlpatterns = [
    path('cria/', views.ContatoCreateView.as_view(),name='cria-contato'),
    path('atualiza/<int:pk>', views.ContatoUpdateView.as_view(),name='atualiza-contato'),
    path('remove/<int:pk>', views.ContatoDeleteView.as_view(),name='remove-contato'),
    path('lista/', views.ContatoListView.as_view(),name='lista-contatos'),
    path('', views.ContatoListView.as_view(),name='home-contatos'),
]

projetoDefinitivo/projetoDefinitivo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from projetoDefinitivo import views
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from django.urls.base import reverse_lazy


urlpatterns = [
    path('', views.home,name='home-page'),

    path('contatos/',include ('contatos.urls'),name="homepage"),

    path('admin/', admin.site.urls),

    path('seguranca/', views.homeSec,name='sec-home'),

    path('seguranca/login', LoginView.as_view(
            template_name='seguranca/usuario.html',
            extra_context={
                'titulo':'Login',
                'tituloPagina':'Login',
                'textoBotao':'Login',
            }
        ),name='sec-login'),

    path('seguranca/logout', LogoutView.as_view(next_page=reverse_lazy('sec-home')
        ),name='sec-logout'),

    path('seguranca/registro', views.registro ,name='sec-registro'),

    path('seguranca/troca_senha', PasswordChangeView.as_view(
        template_name = 'seguranca/usuario.html',
        extra_context = {
            'titulo':'Troca de Senha',
            'tituloPagina':'Troca de senha',
            'textoBotao':'Troca senha',
        },
        success_url=reverse_lazy('sec-password_change_done'),
    ) ,name='sec-password_change'),

    path('seguranca/troca_senha_finalizada/',
        PasswordChangeView.as_view(
            template_name="seguranca/password_change_done.html"), 
        name='sec-password_change_done'),

    path('seguranca/terminaRegistro/<int:pk>',
        UpdateView.as_view(
            template_name= 'seguranca/usuario.html',
            success_url=reverse_lazy('sec-home'),
            extra_context = {
            'titulo':'Termina Registro',
            'tituloPagina':'Termina Registro',
            'textoBotao':'Atualiza',},
            model=User,
            fields=[
                'first_name','last_name','email'
            ],
        ), name='sec-completaDadosUsuario',
    ),

]

projetoDefinitivo/projetoDefinitivo/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.forms import UserCreationForm

def home(request):
    return render(request, 'projetoDefinitivo/index.html')

def homeSec(request):
    return render(request,"seguranca/secHome.html")

def registro(request):
    if request == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('sec-home')
    else:
        form = UserCreationForm()
        context = { 'form': form,
                    'titulo':'Registro',
                    'tituloPagina':'Registro de Usuário',
                    'textoBotao':'Registro',
                    }
        return render(request,
                            'seguranca/registro.html', context)

projetoDefinitivo/projetoDefinitivo/templates/projetoDefinitivo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJANGO</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    {% block css %}
    {% endblock %}
</head>

<body>
    <div class="container" style="font-size: large;">
        <br>

        {% block content %}{% endblock %}
        
    </div>
</body>

</html>

projetoDefinitivo/projetoDefinitivo/templates/projetoDefinitivo/index.html
{% extends 'projetoDefinitivo/base.html' %}
{% load static %}
{% block content %}

{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'contatos/css/estilo.css' %}">
{% endblock %}

    <h1>Homepage</h1>
    <li><a href="{% url 'contatos:home-contatos' %}">Contatos</a></li>
    <li><a href="{% url 'sec-home' %}">Segurança</a></li>
    

{% endblock %}