projetoDefinitivo/contatos/urls.py
from django.urls.conf import path
from contatos import views


app_name = "contatos"

urlpatterns = [
    path('cria/', views.ContatoCreateView.as_view(),name='cria-contato'),
    path('atualiza/<int:pk>', views.ContatoUpdateView.as_view(),name='atualiza-contato'),
    path('remove/<int:pk>', views.ContatoDeleteView.as_view(),name='remove-contato'),
    path('lista/', views.ContatoListView.as_view(),name='lista-contatos'),
    path('', views.ContatoListView.as_view(),name='home-contatos'),
]

projetoDefinitivo/projetoDefinitivo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from projetoDefinitivo import views
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from django.urls.base import reverse_lazy


urlpatterns = [
    path('', views.home,name='home-page'),

    path('contatos/',include ('contatos.urls'),name="homepage"),

    path('admin/', admin.site.urls),

    path('seguranca/', views.homeSec,name='sec-home'),

    path('seguranca/login', LoginView.as_view(
            template_name='seguranca/usuario.html',
            extra_context={
                'titulo':'Login',
                'tituloPagina':'Login',
                'textoBotao':'Login',
            }
        ),name='sec-login'),

    path('seguranca/logout', LogoutView.as_view(next_page=reverse_lazy('sec-home')
        ),name='sec-logout'),

    path('seguranca/registro', views.registro ,name='sec-registro'),

    path('seguranca/troca_senha', PasswordChangeView.as_view(
        template_name = 'seguranca/usuario.html',
        extra_context = {
            'titulo':'Troca de Senha',
            'tituloPagina':'Troca de senha',
            'textoBotao':'Troca senha',
        },
        success_url=reverse_lazy('sec-password_change_done'),
    ) ,name='sec-password_change'),

    path('seguranca/troca_senha_finalizada/',
        PasswordChangeView.as_view(
            template_name="seguranca/password_change_done.html"), 
        name='sec-password_change_done'),

    path('seguranca/terminaRegistro/<int:pk>',
        UpdateView.as_view(
            template_name= 'seguranca/usuario.html',
            success_url=reverse_lazy('sec-home'),
            extra_context = {
            'titulo':'Termina Registro',
            'tituloPagina':'Termina Registro',
            'textoBotao':'Atualiza',},
            model=User,
            fields=[
                'first_name','last_name','email'
            ],
        ), name='sec-completaDadosUsuario',
    ),

]

projetoDefinitivo/contatos/models.py
from django.db import models

# Create your models here.

class Pessoa(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, help_text='Entre o nome')
    idade = models.IntegerField(help_text='Entre a idade')
    salario = models.DecimalField(help_text='Entre o salário', decimal_places=2, 
                                  max_digits=8)
    email = models.EmailField(help_text='Informe o email', max_length=254)
    telefone = models.CharField(help_text='Telefone com DDD e DDI', max_length=20)
    dtNasc = models.DateField(help_text='Nascimento no formato DD/MM/AAAA', 
                              verbose_name='Data de nascimento')
    
    def __str__(self):
        return self.nome
    

projetoDefinitivo/contatos/forms.py
from django import forms
from contatos.models import Pessoa

class ContatoModel2Form(forms.ModelForm):
    
    nome = forms.CharField(
        label='Nome ',
        widget=forms.TextInput(attrs={'class':'w-auto form-control', 'placeholder':'nome'}),
    )
    idade = forms.IntegerField(
        label='Idade ',
        widget=forms.NumberInput(attrs={'class':'w-auto form-control', 'placeholder':'idade'}),
    )
    salario = forms.DecimalField(
        label='Salário ',
        widget=forms.NumberInput(attrs={'class':'w-auto form-control', 'placeholder':'salario'}),
    )
    email = forms.CharField(
        label='Email ',
        widget=forms.EmailInput(attrs={'class':'w-auto form-control', 'placeholder':'email'}),
    )
    telefone = forms.CharField(
        label='Telefone ',
        widget=forms.TextInput(attrs={'class':'w-auto form-control', 'placeholder':'telefone'}),
    )
    dtNasc = forms.DateField(
        input_formats=['%d/%m/%Y'],
        label='Data de Nascimento  ',
        widget=forms.DateInput(attrs={'class':'w-auto form-control', 'placeholder':'dtNasc'}),
    )
    class Meta:
        model = Pessoa
        fields = '__all__'
        labels = {
            'nome': '',
            'idade': '',
            'salario': '',
            'email': '',
            'telefone': '',
            'dtNasc': '',
        }
        helper_texts = {
            'nome': '',
            'idade': '',
            'salario': '',
            'email': '',
            'telefone': '',
            'dtNasc': '',
        }
        widgets = {
            'nome': forms.TextInput(attrs={'class':'form-control', 'placeholder':'nome'}),
            'idade': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'idade'}),
            'salario': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'salario'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'email'}),
            'telefone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'telefone'}),
        }

projetoDefinitivo/contatos/views.py
from django.shortcuts import render, get_object_or_404
from contatos.models import Pessoa
from django.views.generic.base import View
from contatos.forms import ContatoModel2Form
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
# Create your views here.

class ContatoListView(View):
    def get(self, request, *args, **kwargs):
        pessoas = Pessoa.objects.all()
        contexto = { 'pessoas': pessoas, }
        return render(request,'contatos/listaContatos.html',contexto)

class ContatoCreateView(View):
    def get(self, request, *args, **kwargs):
        contexto = { 'formulario': ContatoModel2Form, "titulo":"Cria um Contato", "submitText":"Criar Contato"}
        return render(request,
        "contatos/formContato.html", contexto)
    
    def post(self, request, *args, **kwargs):
        formulario = ContatoModel2Form(request.POST)
        if formulario.is_valid():
            contato = formulario.save()
            contato.save()
            return HttpResponseRedirect(reverse_lazy(
            "contatos:lista-contatos"))
        return render(request,"contatos/formContato.html", {"formulario":formulario, "titulo":"Cria um Contato", "submitText":"Criar Contato"})
    
class ContatoUpdateView(View):
    def get(self,request,pk,*args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        formulario = ContatoModel2Form(instance=pessoa)
        return render(request, 'contatos/formContato.html', 
                      {"formulario":formulario, "titulo":"Atualiza um Contato", "submitText":"Atualizar"})
    
    def post(self, request, pk, *args, **kwargs):
        pessoa = get_object_or_404(Pessoa, pk=pk)
        formulario = ContatoModel2Form(request.POST, instance=pessoa)
        if formulario.is_valid():
            pessoa = formulario.save() # cria uma pessoa com os dados do formulário
            pessoa.save() # salva uma pessoa no banco de dados
            return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))
        else:
            print("nao é valido")
            contexto = {'pessoa': formulario, "titulo":"Atualiza um Contato", "submitText":"Atualizar"}
            return render(request, 'contatos/formContato.html', contexto)

class ContatoDeleteView(View):
    def get(self,request,pk,*args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        contexto = { 'pessoa': pessoa, }
        return render(  request, 
                        'contatos/apagaContato.html', 
                        contexto)

    def post(self, request, pk, *args, **kwargs):
        print("AAAAA")
        pessoa = get_object_or_404(Pessoa, pk=pk)
        pessoa.delete()
        return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))

projetoDefinitivo/contatos/templates/contatos/_vazio.html
{% extends 'projetoDefinitivo/base.html' %}
{% load static %}
{% block content %}
{% include 'contatos/links.html' %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'contatos/css/estilo.css' %}">
{% endblock %}



{% endblock %}

projetoDefinitivo/contatos/templates/contatos/apagaContato.html
{% extends 'projetoDefinitivo/base.html' %}
{% load static %}
{% block content %}
{% include 'contatos/links.html' %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'contatos/css/estilo.css' %}">
{% endblock %}



{% endblock %}

projetoDefinitivo/contatos/templates/contatos/formContato.html
{% extends 'projetoDefinitivo/base.html' %}
{% load static %}
{% block content %}
{% include 'contatos/links.html' %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'contatos/css/estilo.css' %}">
{% endblock %}

<h1>{{ titulo }}</h1>
<br>
<div>
    <form action="" method="POST">
        {% csrf_token %}
        <table class='formulario'>
            {{ formulario.as_table }}
        </table>
        <button type="submit" >{{ submitText }}</button>
    </form>
</div>


{% endblock %}

projetoDefinitivo/contatos/templates/contatos/links.html
<a href="/">
    Home-Page
</a>|
<a href="{% url 'contatos:cria-contato'%}">
    Cria contato
</a>
<hr>

projetoDefinitivo/contatos/templates/contatos/listaContatos.html
{% extends 'projetoDefinitivo/base.html' %}
{% load static %}
{% block content %}
{% include 'contatos/links.html' %}


{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'contatos/css/estilo.css' %}">
{% endblock %}




<h1>Lista de Contatos</h1>
<table class="table table-striped table-sm" style="width: 100%;">
    <tr>
        <th>email</th>
        <th>Idade</th>
        <th>Salário</th>
        <th>Ações disponíveis</th>
    </tr>
    {% for pessoa in pessoas %}
    <tr>
        <td><a href="{% url 'contatos:atualiza-contato' pk=pessoa.id %}">{{ pessoa.nome }}</a></td>
        <td>{{pessoa.idade }}</td>
        <td>{{ pessoa.salario }}</td>
        <td>
            <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Apagar
            </a>
        </td>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Deseja apagar este contato?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <form action="{% url 'contatos:remove-contato' pk=pessoa.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Sim</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </tr>
    {% empty %}
    <tr>
        <th colspan="5">Ainda não tem contatos cadastrados</th>
    </tr>
    {% endfor %}
</table>





{% endblock %}